version: "3"
services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - rails-api
      - go-service

  db:
    image: mysql:8.4.7
    volumes:
      - db-data:/var/lib/mysql
    env_file: .env

  redis:
    image: redis:8.2

  sidekiq:
    depends_on:
      - db
      - redis
    build:
      context: .
      dockerfile: rails_api/Dockerfile
    env_file: .env
    entrypoint: "bundle exec sidekiq"
    stdin_open: true
    tty: true
    volumes:
      - ./rails_api:/app

  rails-api:
    build:
      context: .
      dockerfile: rails_api/Dockerfile
    volumes:
      - ./rails_api:/app
    env_file: .env
    entrypoint: /app/entrypoint.sh
    stdin_open: true
    tty: true
    depends_on:
      - db
      - redis
      - elasticsearch

  go-service:
    build:
      context: ./go_service
      dockerfile: Dockerfile
    env_file: .env
    depends_on:
      - redis

  elasticsearch:
    image: elasticsearch:7.17.27
    environment:
      - discovery.type=single-node
      - ELASTIC_PASSWORD=password
      - "ES_JAVA_OPTS=-Xms1G -Xmx1G"
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200

volumes:
  db-data:
  elasticsearch-data: